language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify
deploy:
  provider: gae
  keyfile: calendar-monster-secret.json
  project: calendar-monster
  skip_cleanup: true
  config: src/main/appengine/app.yaml
  verbosity: info
#- gcloud components install app-engine-java
before_install:
- openssl aes-256-cbc -K $encrypted_05278cc033a1_key -iv $encrypted_05278cc033a1_iv
  -in calendar-monster-secret.json.enc -out calendar-monster-secret.json
  -d
