# Yaml file reference: http://www.deepzeafish.xyz/yaml-properties-spring-boot.html
#
#
#

spring:
  profiles:
    active: dev
app:
# look at springboot GitInfoContributor it will expose this for you via the git.properties property
  sha-1: @buildNumber@
  git.id: @git.commit.id.abbrev@

---
spring:
  profiles: dev
logging:
  level:
    org.springframework.web: debug
    com.cmcllc: trace
app:
  cleanup:
    delay: 60000
    deletetime: 4
    onexit: true

---
# this section is good when interacting with Spring classes/services
# for POJO testing, you will need a logback.xml file
spring:
  profiles: test
logging:
  level:
    com.cmcllc: trace

---
spring:
  profiles: prod
logging:
  level:
    root: info
    com.cmcllc: warn
app:
  cleanup:
    onexit: true
    deletetime: 2
    delay: 900000
