# Yaml file reference: http://www.deepzeafish.xyz/yaml-properties-spring-boot.html
#
#
#

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
logging:
  level:
    org.springframework.web: debug
    com.cmcllc: trace
app:
  cleanup:
    delay: 60000
    deletetime: 4
    onexit: true
server:
    port: 9000

---
# this section is good when interacting with Spring classes/services
# for POJO testing, you will need a logback.xml file
spring:
  profiles: test
logging:
  level:
    com.cmcllc: trace

---
spring:
  profiles: prod
logging:
  level:
    root: info
    com.cmcllc: warn
app:
  cleanup:
    onexit: true
    deletetime: 2
    delay: 900000
